# SPDX-FileCopyrightText: 2025 Jorge Teixeira Crespo
# SPDX-License-Identifier: CC0-1.0
name: Build PDF on PR

on:
  pull_request:
    paths:
      - '**.tex'
      - '**.sty'
      - 'anexos/**'
      - 'bibliografia/**'
      - 'contido/**'
      - 'imaxes/**'
      - 'portada/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: memoria_tfg.tex
          latexmk_use_xelatex: true
      - id: upload-pdf
        name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: memoria_tfg.pdf
      - name: Comment on PR with PDF link
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Your thesis document is ready to download:

            👉 [Download memoria_tfg.pdf][1]

            [1]: https://github.com/jorgeteixe/thesis/actions/runs/${{ github.run_id }}/artifacts/${{ steps.upload-pdf.outputs.artifact-id }}
