# SPDX-FileCopyrightText: 2025 Jorge Teixeira Crespo
# SPDX-License-Identifier: GPL-3.0-or-later
name: Build PDF on PR open

on: [pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: memoria_tfg.tex
          latexmk_use_xelatex: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: memoria_tfg.pdf
